In [1]:
import torch  


In [3]:
idx = torch.cat([torch.tensor([0]) for _ in range(4)])
print(idx)
y_labels = torch.rand(10, 5)
y_labels

tensor([0, 0, 0, 0])


tensor([[0.9719, 0.2814, 0.3171, 0.5629, 0.9773],
        [0.7925, 0.4719, 0.1021, 0.7571, 0.1956],
        [0.3774, 0.1023, 0.2314, 0.4613, 0.9517],
        [0.9982, 0.1183, 0.4094, 0.0423, 0.6275],
        [0.4633, 0.7323, 0.9889, 0.6752, 0.2036],
        [0.5313, 0.0596, 0.3342, 0.7812, 0.2877],
        [0.5240, 0.9567, 0.0707, 0.4474, 0.8893],
        [0.7265, 0.3806, 0.9246, 0.7496, 0.9783],
        [0.5588, 0.9052, 0.7207, 0.4269, 0.4279],
        [0.0428, 0.6816, 0.4278, 0.4376, 0.5327]])

In [4]:
print(y_labels[:, idx].shape)

torch.Size([10, 4])


In [7]:
torch.split(y_labels, [2, 8])

(tensor([[0.9719, 0.2814, 0.3171, 0.5629, 0.9773],
         [0.7925, 0.4719, 0.1021, 0.7571, 0.1956]]),
 tensor([[0.3774, 0.1023, 0.2314, 0.4613, 0.9517],
         [0.9982, 0.1183, 0.4094, 0.0423, 0.6275],
         [0.4633, 0.7323, 0.9889, 0.6752, 0.2036],
         [0.5313, 0.0596, 0.3342, 0.7812, 0.2877],
         [0.5240, 0.9567, 0.0707, 0.4474, 0.8893],
         [0.7265, 0.3806, 0.9246, 0.7496, 0.9783],
         [0.5588, 0.9052, 0.7207, 0.4269, 0.4279],
         [0.0428, 0.6816, 0.4278, 0.4376, 0.5327]]))

In [17]:
a = torch.rand(2, 10, 4) 

for i, c in enumerate(a.split([2, 2], -1)): 
    print(c[i].shape)



torch.Size([10, 2])
torch.Size([10, 2])


In [10]:
a = torch.rand(2, 4) 
b = torch.rand(5, 4)

tl = torch.maximum(a[:, None, :2], b[None, :, :2])
br = torch.maximum(a[:, None, :2], b[None, :, :2])

(br - tl).shape

torch.Size([2, 5, 2])

In [7]:
a = torch.rand(2, 10) 
idx = torch.randint(0, 1, (3, 3))
print(idx)
a[idx].shape

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


torch.Size([3, 3, 10])

In [8]:
print(a)
a[idx]

tensor([[0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117, 0.7561,
         0.4919],
        [0.5690, 0.3317, 0.8103, 0.9674, 0.9753, 0.6589, 0.6841, 0.2472, 0.6650,
         0.9886]])


tensor([[[0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919],
         [0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919],
         [0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919]],

        [[0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919],
         [0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919],
         [0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919]],

        [[0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919],
         [0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919],
         [0.0698, 0.8550, 0.3573, 0.1487, 0.7982, 0.2791, 0.7120, 0.5117,
          0.7561, 0.4919]]])

In [9]:
target_classes_o = torch.rand(16*20)
target_classes = torch.full((16, 100), 1) 
target_classes[idx] = target_classes_o
print(target_classes[idx].shape)


RuntimeError: shape mismatch: value tensor of shape [320] cannot be broadcast to indexing result of shape [3, 3, 100]